### ISSUE TITLE
Setup ESLint [Beginners]

### ISSUE THREAD

**Issue by ashokdey** [ashokdey/private-io#10]
What you have to do?

- [x] Get into the **develop** branch
- [x] Setup **ESLint** with **AirBnB** rules
- [x] Test that ESLint setup is working properly
- [x] Add NPM script to check lint errors

Open you PR after checking all the above things and your PR should point to the **develop** branch not the **master**

**Comment by Bryze** [comment]
@ashokdey  Submitted a pr #12  :)

**Comment by ashokdey** [comment]
PR #12 closes this.
