### ISSUE TITLE
Cover Spelling Mistake

### ISSUE THREAD

**Issue by leonlafa** [ashokdey/private-io#15]
There is a spelling mistake on the cover page:
<img width="618" alt="Screenshot 2019-10-06 at 14 40 09" src="https://user-images.githubusercontent.com/44982724/66270085-53eeed00-e847-11e9-9241-74bd2eff07e8.png">

Should read **Support**

**Comment by ashokdey** [comment]
Thank you @leonlafa you can open a PR for the same I will merge it.

**Comment by leonlafa** [comment]
Done 😄
