### ISSUE TITLE
Fix 'Enter Name' bug [React.js Beginners]

### ISSUE THREAD

**Issue by ashokdey** [ashokdey/private-io#19]
On the main page, if you try to add a name that is less than 4 chars, the input field has a bug that carries the place holder text as the input text. 

Notes:
- Make sure other parts of the app is not breaking
- Make sure ESLint rules are not breaking
- Make sure to open your PR in **Develop** branch

⭐️ If you like the work, do star the repo ⭐️ 

All the best.

**Comment by PranjalAgni** [comment]
Can I work on this?

**Comment by ashokdey** [comment]
Sure @PranjalAgni, I am assigning you this issue, you got 10 hrs to submit this and also star the repo if you liked it.

**Comment by haichuan0424** [comment]
I'd like to work on this too if the other person does not submit PR within your requested time.

**Comment by ashokdey** [comment]
#21 by @PranjalAgni closes this. Good to see your interest @haichuan0424, you can look at #20
