### ISSUE TITLE
Update the NPM packages [React + Node Beginners]

### ISSUE THREAD

**Issue by ashokdey** [ashokdey/private-io#8]
Do the following:
- [ ] Run the app after cloning
  - [ ] Open issues if the app is crashing
- [ ] Update the packages
- [ ] Make sure the app is running properly
- [ ] Check for **npm audit**

**Note**: 
- Open PR only if things are not breaking after the update. 
- Open PR in the **develop** branch

Thanks

**Comment by itsaakashpatel** [comment]
@ashokdey Submitted PR, Thanks!

**Comment by ashokdey** [comment]
Thanks, @itsaakashpatel, can you run a final check using **npm-audit**? Just added in the issue. Also, can you take up the issue of ESLint #10?

**Comment by ashokdey** [comment]
#11 by @itsaakashpatel closes this. Thanks for the contributions 🍷
