### ISSUE TITLE
Fix "No connection Alert" [Node / React Beginners]

### ISSUE THREAD

**Issue by ashokdey** [ashokdey/private-io#9]
When you access the live app here: [PrivateIO](https://privateio.herokuapp.com)

Once you enter your name and click start, you'll notice an alert saying **No connection, please refresh** (Screenshot is given below)

![image](https://user-images.githubusercontent.com/4851057/66264572-6d7f3d00-e825-11e9-943b-69b9bc11bb67.png)

Go ahead and fix this, raise your PR in the **develop** branch

**Comment by imravichhetri** [comment]
@ashokdey  I would like to work on this.

**Comment by ashokdey** [comment]
Cool @imravichhetri, assigning you.

**Comment by imravichhetri** [comment]
#13 Please check this PR.

**Comment by ashokdey** [comment]
> #13 Please check this PR.

Great work! 🍷  Drop me a DM in twitter [ashokdey_](https://twitter.com/ashokdey_)

**Comment by r4de** [comment]
Hi there...nice Project, but still "No connection to server, Please Refresh"

**Comment by ashokdey** [comment]
@r4de the deployment pipe seems broken.
